services:
  api:
    build: ./api
    stdin_open: true
    container_name: api
    restart: always
    volumes:
      - showrunner-data:/var/lib/showrunner/api
    ports: 
      - "3000:3000"
volumes:
  showrunner-data: